config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'
  
  resources :tickets, except: [:index, :edit] do
    get '/export', to: 'export#show'

    resources :airlines, except: [:index, :show]  
    resources :routes, except: [:index, :show]  
    resources :passengers, except: [:index, :show]
  end

  resources :users
  
  resources :manage_passengers do
    collection do
      get '/search', to: 'manage_passengers#search'
    end
  end

  get '/suggestions', to: 'manage_passengers#suggest'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :rememberable, :validatable

  has_many :passengers
  
  enum user_role: %i[staff administrator]

  def destroy
    update_attributes(deactivated: true) unless deactivated
  end

  def active_for_authentication?
    super && !deactivated
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'Nhân viên đã được tạo thành công'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'Nhân viên đã được cập nhật thành công'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Đã khóa người dùng'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :deactivated, :user_role)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: 'form-box form-box--c') do |f| %>
  <% if user.errors.any? %>
    <div class="message alert" data-controller="alert">
      <div class="message-content">
        <h5><%= pluralize(user.errors.count, "error") %></h5>
        <ul class="list">
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>

      <a class="close" nohref data-action="click->alert#close"></a>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: 'Ví dụ: abc@mail.com' %>
  </div>

  <div class="field">
    <%= f.label :user_role, "Phân quyền" %>
    <%= f.select :user_role, options_for_select([['Nhân viên', 'staff'], ['Quản trị viên', 'administrator']], :selected => user.user_role), {}, {} %>
  </div>

  <div class="field">
    <%= f.label :password, 'Mật khẩu' %>
    <%= f.password_field :password, placeholder: 'Tối thiểu 6 ký tự' %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, 'Nhập lại mật khẩu' %>
    <%= f.password_field :password_confirmation, placeholder: 'Tối thiểu 6 ký tự' %>
  </div>

  <div class="field">
    <%= f.check_box :deactivated %> Khóa người dùng
  </div>

  <div class="actions">
    <%= f.submit "Tạo", class: 'btn primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="section flex align-items--center justify-content--between">
        <div class="section-title">Cập nhật nhân viên</div>
        
        <a href="<%= users_path %>" class="btn primary">
          <i class="fe fe-arrow-left btn-icon"></i>
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="section flex align-items--center justify-content--between">
        <div class="section-title">Thành viên</div>
        
        <% if current_user.user_role == 'administrator' %>
          <a href="<%= new_user_path %>" class="btn primary">
            <i class="fe fe-plus"></i>
            Thêm thành viên
          </a>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <table class="c-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Phân quyền</th>
            <th>Trạng thái</th>
            <th>Ngày tạo</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td data-label="ID"><%= user.id %></td>
              <td data-label="Email"><%= user.email %></td>
              <td data-label="Phân quyền">
                <% if user.user_role == "staff" %>
                  Nhân viên
                <% else %>
                  Quản trị viên
                <% end %>
              </td>
              <td data-label="Trạng thái">
                <% if user.deactivated == true %>
                  Tạm khóa
                <% else %>
                  Hoạt động
                <% end %>
              </td>
              <td data-label="Ngày tạo"><%= user.created_at .strftime("%d/%m/%Y") %></td>
              <td>
                <% if current_user.user_role == 'administrator' %>
                  <div class="btn-group">
                    <%= link_to 'Cập nhật', edit_user_path(user), class: 'btn mini' %>
                    <%= link_to 'Khóa thành viên', user, method: :delete, data: { confirm: 'Bạn có chắc muốn khóa người dùng này?' }, class: 'btn mini warning' %>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="section flex align-items--center justify-content--between">
        <div class="section-title">Thêm nhân viên</div>
        
        <a href="<%= users_path %>" class="btn primary">
          <i class="fe fe-arrow-left btn-icon"></i>
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>