config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'
  
  resources :tickets, except: [:index, :edit] do
    get '/export', to: 'export#show'

    resources :airlines, except: [:index, :show]  
    resources :routes, except: [:index, :show]  
    resources :passengers, except: [:index, :show]
  end

  resources :users
  
  resources :manage_passengers do
    collection do
      get '/search', to: 'manage_passengers#search'
    end
  end

  get '/suggestions', to: 'manage_passengers#suggest'
end

app/controllers/manage_passengers_controller.rb
class ManagePassengersController < ApplicationController
  before_action :set_passenger, only: [:edit, :update, :destroy]

  layout 'pdf', only: [:search]

  # GET /passengers
  def index
    if current_user.user_role == 'administrator'
      @results = Passenger.passenger_search(params[:q]).paginate(page: params[:page], per_page: 20)
      @passengers = Passenger.all.order('created_at ASC').paginate(page: params[:page], per_page: 20)
    else
      @results = Passenger.where(user_id: current_user).passenger_search(params[:q]).paginate(page: params[:page], per_page: 20)
      @passengers = Passenger.all.order('created_at ASC').where(user_id: current_user).paginate(page: params[:page], per_page: 20)
    end
  end

  def search
    @results = Passenger.where(user_id: current_user).passenger_search(params[:q])
    @pass_contact = Passenger.all.order('created_at DESC').where(user_id: current_user).paginate(page: params[:page], per_page: 5)
  end

  def suggest
    @names = Passenger.where(user_id: current_user).passenger_search(params[:name])

    render layout: false
  end

  def new
    @passenger = Passenger.new
  end

  def create
    @passenger = Passenger.new(passenger_params)

    if @passenger.save
      redirect_to manage_passengers_path, notice: 'Hành khách đã được thêm thành công'
    else
      render :new
    end
  end

  # GET /passengers/1/edit
  def edit
  end

  # PATCH/PUT /passengers/1
  def update
    if @passenger.update(passenger_params)
      redirect_to manage_passengers_path, notice: 'Hành khách đã được cập nhật thành công'
    else
      render :edit
    end
  end

  def destroy
    @passenger.destroy
    redirect_to manage_passengers_url, notice: 'Đã xóa hành khách'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def passenger_params
      params.require(:passenger).permit(:full_name, :dob, :phone_number, :nid, :pid, :seat_type, :ticket_class, :extra, :user_id, :ticket_id)
    end
end

app/views/manage_passengers/_form.html.erb
<%= form_for passenger, url: manage_passenger_path(passenger), html: { class: 'form-box form-box--c' } do |f| %>
  <% if passenger.errors.any? %>
    <div class="message alert" data-controller="alert">
      <div class="message-content">
        <h5><%= pluralize(passenger.errors.count, "error") %></h5>
        <ul class="list">
          <% passenger.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>

      <a class="close" nohref data-action="click->alert#close"></a>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :full_name, "Họ tên" %>
    <%= f.text_field :full_name, required: true %>
  </div>

  <div class="field">
    <%= f.label :dob, "Ngày sinh" %>
    <%= f.text_field :dob,
      data: {
        controller: "date",
        date_alt_format: "l, j M Y",
        date_alt_input: true
      }
    %>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="field">
        <%= f.label :nid, "Chứng minh nhân dân" %>
        <%= f.text_field :nid %>
      </div>
    </div>

    <div class="col-6">
      <div class="field">
        <%= f.label :pid, "Số hộ chiếu" %>
        <%= f.text_field :pid %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :phone_number, "Số điện thoại" %>
    <%= f.text_field :phone_number, required: true %>
  </div>

  <div class="row">
    <div class="col-4">
      <div class="field">
        <%= f.label :seat_type, "Loại ghế" %>
        <%= f.select :seat_type, options_for_select(Passenger.seat_types.keys.map { |w| [w.upcase, w] }), {}, {} %>
      </div>
    </div>

    <div class="col-4">
      <div class="field">
        <%= f.label :ticket_class, "Hạng vé" %>
        <%= f.select :ticket_class, options_for_select(Passenger.ticket_classes.keys.map { |w| [w.upcase, w] }), {}, {} %>
      </div>
    </div>

    <div class="col-4">
      <div class="field">
        <%= f.label :extra, "Hành lý mang thêm (Kg)" %>
        <%= f.number_field :extra, max: 100 %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Cập nhật", class: 'btn primary' %>
  </div>
<% end %>

app/views/manage_passengers/_new-form.html.erb
<%= form_for passenger, url: manage_passengers_path, html: { class: 'form-box form-box--c' } do |f| %>
  <% if passenger.errors.any? %>
    <div class="message alert" data-controller="alert">
      <div class="message-content">
        <h5><%= pluralize(passenger.errors.count, "error") %></h5>
        <ul class="list">
          <% passenger.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>

      <a class="close" nohref data-action="click->alert#close"></a>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :ticket_id, value: Ticket.first.id %>

  <div class="field">
    <%= f.label :full_name, "Họ tên" %>
    <%= f.text_field :full_name, required: true %>
  </div>

  <div class="field">
    <%= f.label :dob, "Ngày sinh" %>
    <%= f.text_field :dob,
      data: {
        controller: "date",
        date_alt_format: "l, j M Y",
        date_alt_input: true
      }
    %>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="field">
        <%= f.label :nid, "Chứng minh nhân dân" %>
        <%= f.text_field :nid %>
      </div>
    </div>

    <div class="col-6">
      <div class="field">
        <%= f.label :pid, "Số hộ chiếu" %>
        <%= f.text_field :pid %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :phone_number, "Số điện thoại" %>
    <%= f.text_field :phone_number, required: true %>
  </div>

  <div class="actions">
    <%= f.submit "Cập nhật", class: 'btn primary' %>
  </div>
<% end %>

app/views/manage_passengers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="section flex align-items--center justify-content--between">
        <div class="section-title">Cập nhật hành khách</div>
        
        <a href="<%= manage_passengers_path %>" class="btn primary">
          <i class="fe fe-arrow-left btn-icon"></i>
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= render 'form', passenger: @passenger %>
    </div>
  </div>
</div>

app/views/manage_passengers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="section flex align-items--center justify-content--between">
        <div class="section-title">Hành khách</div>

        <a href="<%= new_manage_passenger_path %>" class="btn primary">
            <i class="fe fe-plus"></i>
            Thêm hành khách
          </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= form_tag(manage_passengers_path, method: :get, class: 'form') do %>
        <input type="text" placeholder="Tìm kiếm" name="q" class="input">
      <% end %>
    </div>

    <div class="col-12">
      <% if @results.present? %>
        <table class="c-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Họ Tên</th>
              <th>Ngày sinh</th>
              <th>CMND/hộ chiếu</th>
              <th>Số điện thoại</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @results.each do |passenger| %>
              <tr class="export-pass">
                <td data-label="ID"><%= passenger.id %></td>
                <td data-label="Họ Tên"><%= passenger.full_name %></td>
                <td data-label="Ngày sinh"><%= passenger.dob.present? ? passenger.dob.strftime("%d/%m/%Y") : '' %></td>
                <td data-label="CMND/hộ chiếu"><%= passenger.nid.present? ? passenger.nid : passenger.pid %></td>
                <td data-label="Số điện thoại"><%= passenger.phone_number %></td>
                <td>
                  <div class="btn-group">
                    <%= link_to 'Cập nhật', edit_manage_passenger_path(passenger), class: 'btn mini' %>
                    <%= link_to 'Xóa', manage_passenger_path(passenger), method: :delete, data: { confirm: 'Bạn có chắc muốn xóa hành khách này?' }, class: 'btn mini warning' %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= will_paginate @results %>
      <% elsif @passengers.present? %>
        <table class="c-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Họ Tên</th>
              <th>Ngày sinh</th>
              <th>CMND/hộ chiếu</th>
              <th>Số điện thoại</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @passengers.each do |passenger| %>
              <tr class="export-pass">
                <td data-label="ID"><%= passenger.id %></td>
                <td data-label="Họ Tên"><%= passenger.full_name %></td>
                <td data-label="Ngày sinh"><%= passenger.dob.present? ? passenger.dob.strftime("%d/%m/%Y") : '' %></td>
                <td data-label="CMND/hộ chiếu"><%= passenger.nid.present? ? passenger.nid : passenger.pid %></td>
                <td data-label="Số điện thoại"><%= passenger.phone_number %></td>
                <td>
                  <div class="btn-group">
                    <%= link_to 'Cập nhật', edit_manage_passenger_path(passenger), class: 'btn mini' %>
                    <%= link_to 'Xóa', manage_passenger_path(passenger), method: :delete, data: { confirm: 'Bạn có chắc muốn xóa hành khách này?' }, class: 'btn mini warning' %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= will_paginate @passengers %>
      <% else %>
        <div class="placeholder">
          <div class="placeholder-header">
            <i class="fe fe-search"></i>
            Chưa có <strong>khách hàng</strong> nào trên hệ thống.
          </div>

          <a href="<%= new_manage_passenger_path %>"class="btn primary">Tạo khách hàng</a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/manage_passengers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="section flex align-items--center justify-content--between">
        <div class="section-title">Thêm hành khách</div>
        
        <a href="<%= manage_passengers_path %>" class="btn primary">
          <i class="fe fe-arrow-left btn-icon"></i>
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= render 'new-form', passenger: @passenger %>
    </div>
  </div>
</div>

app/views/manage_passengers/search.html.erb
<%= form_tag(search_manage_passengers_path, method: :get, class: 'form') do %>
  <input type="text" placeholder="Tìm kiếm" name="q" class="input">
<% end %>

<ul class="modal-passengers">
  <% if @results.present? %>
    <% @results.each do |passenger| %>
      <li>
        <div class="pass-info">
          <h5><%= passenger.full_name %></h5>
          <p><span>CMND/Hộ chiếu:</span> <%= passenger.nid.present? ? passenger.nid : passenger.pid %></p>
        </div>

        <div class="pass-action"
          data-controller="populate"
          data-populate-full_name="<%= passenger.full_name %>"
          data-populate-nid="<%= passenger.nid %>"
          data-populate-pid="<%= passenger.pid %>"
          data-populate-dob="<%= passenger.dob %>"
          data-populate-phone_number="<%= passenger.phone_number %>"
        >
          <button class="btn primary" data-action="click->populate#add">Thêm</button>
        </div>
      </li> 
    <% end %>
  <% else %>
    <% @pass_contact.each do |passenger| %>
      <li>
        <div class="pass-info">
          <h5><%= passenger.full_name %></h5>
          <p><span>CMND/Hộ chiếu:</span> <%= passenger.nid.present? ? passenger.nid : passenger.pid %></p>
        </div>

        <div class="pass-action"
          data-controller="populate"
          data-populate-full_name="<%= passenger.full_name %>"
          data-populate-nid="<%= passenger.nid %>"
          data-populate-pid="<%= passenger.pid %>"
          data-populate-dob="<%= passenger.dob %>"
          data-populate-phone_number="<%= passenger.phone_number %>"
        >
          <button class="btn primary" data-action="click->populate#add">Thêm</button>
        </div>
      </li> 
    <% end %>

    <%= will_paginate @pass_contact %>
  <% end %>
</ul>

app/views/manage_passengers/suggest.html.erb
<ul>
  <% if @names.present? %>
    <% @names.each do |passenger| %>
      <li data-controller="populate"
          data-populate-full_name="<%= passenger.full_name %>"
          data-populate-nid="<%= passenger.nid %>"
          data-populate-pid="<%= passenger.pid %>"
          data-populate-dob="<%= passenger.dob %>"
          data-populate-phone_number="<%= passenger.phone_number %>"
      >
        <div class="pass-info" data-action="click->populate#add">
          <h5><%= passenger.full_name %></h5>
          <p><span>CMND/Hộ chiếu:</span> <%= passenger.nid.present? ? passenger.nid : passenger.pid %></p>
        </div>
      </li> 
    <% end %>
  <% else %>
    <p class="search-null">Không có khách hàng liên quan</p>
  <% end %>
</ul>