config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'
  
  resources :tickets, except: [:index, :edit] do
    get '/export', to: 'export#show'

    resources :airlines, except: [:index, :show]  
    resources :routes, except: [:index, :show]  
    resources :passengers, except: [:index, :show]
  end

  resources :users
  
  resources :manage_passengers do
    collection do
      get '/search', to: 'manage_passengers#search'
    end
  end

  get '/suggestions', to: 'manage_passengers#suggest'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_rich_text :note

  has_many :airlines, dependent: :destroy
  has_many :routes, dependent: :destroy
  has_many :passengers, dependent: :destroy

  enum ticket_type: %i[oneway roundtrip]

  validates :tid, length: { in: 1..180 }
  validates :ticket_type, presence: true, inclusion: { in: Ticket.ticket_types.keys }
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets/1
  def show
    @airlines = @ticket.airlines
    @routes = @ticket.routes
    @passengers = @ticket.passengers
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to ticket_path(@ticket), notice: 'Hóa đơn đã được tạo thành công'
    else
      render :new
    end
  end

  # PATCH/PUT /tickets/1
  def update
    if @ticket.update(ticket_params)
      redirect_to ticket_path(@ticket), notice: 'Hóa đơn đã được cập nhật thành công'
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  def destroy
    @ticket.destroy
    redirect_to root_url, notice: 'Đã xóa hóa đơn'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ticket_params
      params.require(:ticket).permit(:airline_name, :airline_id, :tid, :booking_date, :ticket_type, :airline_logo, :note)
    end
end

app/views/tickets/components/_airline.html.erb
<div class="airline-form block">
  <h4>
    Hãng bay
    <% if @ticket.ticket_type == "roundtrip" %>
      <%= airlines.count + 1 %>
    <% end %>
  </h4>

  <%= form_for [@ticket, airlines.new], html: { class: 'form-box' } do |f| %>      
    <div class="row">
      <div class="col-6">
        <div class="field">
          <%= f.label :name, "Tên hãng bay" %>
          <%= f.text_field :name, placeholder: 'Ví dụ: Vietnam Airlines, Vietjet,...', required: true %>
        </div>
      </div>

      <div class="col-6">
        <div class="field">
          <%= f.label :aid, "Số hiệu chuyến bay" %>
          <%= f.text_field :aid, placeholder: 'Ví dụ: VJ12345,...', required: true %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :logo, "Logo hãng bay" %>
      <%= f.file_field :logo, required: true %>
    </div>

    <div class="actions">
      <%= f.submit "Thêm", class: 'btn primary' %>
    </div>
  <% end %>
</div>

app/views/tickets/components/_contact.html.erb
<div id="modal" class="modal" data-controller="modal">
  <div class="modal-wrapper">
    <div class="modal-header">
      <h4>Danh bạ hành khách</h4>
      <a nohref class="close" data-action="modal#hide"></a>
    </div>
    
    <div class="modal-content">
      <iframe src="<%= search_manage_passengers_url %>" width="100%" height="490px" frameborder="0"></iframe>
    </div>
  </div>
</div>

app/views/tickets/components/_passenger.html.erb
<div class="passenger-form block">
  <div class="block-flex" data-controller="modal">
    <h4>Hành khách</h4>
    <a nohref class="btn" data-action="modal#open">Thêm từ danh bạ</a>
  </div>

  <%= form_for [@ticket, passengers.new], html: { class: 'form-box' } do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="field" data-controller="suggestions">
      <%= f.label :full_name, "Họ tên" %>
      <%= f.text_field :full_name, autofocus: true, placeholder: 'Nguyễn Văn A, Trần Văn C,...', required: true, data: { target: 'suggestions.searchItem', action:  'input->suggestions#requestSearch' } %>
    
      <div class="search-results" data-target="suggestions.searchResults">
        <ul>
          <li class="searching-interim">
            <span class="result-secondary">Searching....</span>
          </li>
        </ul>
      </div>
    </div>

    <div class="field">
      <%= f.label :dob, "Ngày sinh" %>
      <%= f.text_field :dob,
        data: {
          controller: "date",
          date_alt_format: "l, j M Y",
          date_alt_input: true
        }
      %>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="field">
          <%= f.label :nid, "Chứng minh nhân dân" %>
          <%= f.text_field :nid %>
        </div>
      </div>

      <div class="col-6">
        <div class="field">
          <%= f.label :pid, "Số hộ chiếu" %>
          <%= f.text_field :pid %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :phone_number, "Số điện thoại" %>
      <%= f.text_field :phone_number, required: true %>
    </div>

    <div class="row">
      <div class="col-4">
        <div class="field">
          <%= f.label :seat_type, "Loại ghế" %>
          <%= f.select :seat_type, options_for_select(Passenger.seat_types.keys.map { |w| [w.upcase, w] }), {}, {} %>
        </div>
      </div>

      <div class="col-4">
        <div class="field">
          <%= f.label :ticket_class, "Hạng vé" %>
          <%= f.select :ticket_class, options_for_select(Passenger.ticket_classes.keys.map { |w| [w.upcase, w] }), {}, {} %>
        </div>
      </div>

      <div class="col-4">
        <div class="field">
          <%= f.label :extra, "Hành lý mang thêm" %>
          <%= f.text_field :extra %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :more_extra, "Dịch vụ kèm theo" %>
      <%= f.text_field :more_extra %>
    </div>

    <div class="actions">
      <%= f.submit "Thêm", class: 'btn primary' %>
    </div>
  <% end %>
</div>

<%= render 'tickets/components/contact', pass_contact: @pass_contact %>

app/views/tickets/components/_route.html.erb
<div class="route-form block">
  <h4>
    Hành trình
    <% if @ticket.ticket_type == "roundtrip" %>
      <%= routes.count + 1 %>
    <% end %>
  </h4>

  <%= form_for [@ticket, routes.new], html: { class: 'form-box' } do |f| %>        
    <div class="row">
      <div class="col-6">
        <div class="field">
          <%= f.label :depart_time, "Thời điểm khởi hành" %>
          <%= f.text_field :depart_time,
            data: {
              controller: "date"
            }
          %>
        </div>
      </div>

      <div class="col-6">
        <div class="field">
          <%= f.label :depart_place, "Nơi khởi hành" %>
          <%= f.text_field :depart_place, id: "depart_place", required: true %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="field">
          <%= f.label :arrival_time, "Thời điểm đến" %>
          <%= f.text_field :arrival_time,
            data: {
              controller: "date"
            }
          %>
        </div>
      </div>

      <div class="col-6">
        <div class="field">
          <%= f.label :arrival_place, "Nơi đến" %>
          <%= f.text_field :arrival_place, id: "arrival_place", required: true %>
        </div>
      </div>
    </div>

    <div id="transit" class="field" data-controller="addition">
      <%= f.label :transit, "Quá cảnh" %>
      <a nohref id="transit-btn" class="btn mini secondary no-select" data-action="click->addition#add_transit">Bật quá cảnh</a>
    </div>

    <div id="transit-logo" class="field hide">
      <%= f.label :transit_airline_logo, "Logo hãng bay" %>
      <%= f.file_field :transit_airline_logo %>
    </div>

    <div class="field">
      <%= f.label :duration, "Tổng thời gian hành trình" %>
      <%= f.text_field :duration %>
    </div>

    <div class="actions">
      <%= f.submit "Thêm", class: 'btn primary' %>
    </div>
  <% end %>
</div>