config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'
  
  resources :tickets, except: [:index, :edit] do
    get '/export', to: 'export#show'

    resources :airlines, except: [:index, :show]  
    resources :routes, except: [:index, :show]  
    resources :passengers, except: [:index, :show]
  end

  resources :users
  
  resources :manage_passengers do
    collection do
      get '/search', to: 'manage_passengers#search'
    end
  end

  get '/suggestions', to: 'manage_passengers#suggest'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(link_path)
    "active" if request.fullpath.include?(link_path)
  end

  def export_date(date)
    date = Time.parse(date)
    date.strftime('%A, %d %b %Y')
  end
end

app/views/application/_alert.html.erb
<% flash.each do |key, value| %>
  <div class="<%= key %> message" data-controller="alert">
    <div class="message-content">
      <h5><%= key %></h5>
      <%= value %>
    </div>
    
    <a class="close" nohref data-action="click->alert#alert_close"></a>
  </div>
<% end %>

app/views/application/_header.html.erb
<div class="site-header flex align-items--center" data-controller="canvas">
  <div class="site-header__logo flex align-items--center justify-content--center">
    <div class="site-menu" data-action="click->canvas#open">
      <span></span>
      <span></span>
      <span></span>
    </div>

    <a href="<%= root_path %>" class="site-header__title">
      <%= image_tag 'aatrip-logo' %>
    </a>
  </div>

  <div id="canvas" class="site-header__canvas">
    <nav class="site-header__nav">
      <a href="<%= root_path %>">Hóa đơn</a>
      <a href="<%= manage_passengers_path %>" class="<%= is_active?(manage_passengers_path) %>">Hành khách</a>

      <% if current_user.user_role == "administrator" %>
        <a href="<%= users_path %>" class="<%= is_active?(users_path) %>">Thành viên</a>
      <% end %>
    </nav>

    <div class="site-header__user flex align-items--center">
      <img src="https://ui-avatars.com/api/?name=<%= current_user.email %>" alt="Profile">
      
      <div class="user">
        <div class="user-email"><%= current_user.email %></div>
        <%= link_to 'Đăng xuất', destroy_user_session_path, method: :delete %>
      </div>
    </div>
  </div>

  <div class="site-header__right flex align-items--center">
    <nav class="site-header__nav">
      <a href="<%= root_path %>">Hóa đơn</a>
      <a href="<%= manage_passengers_path %>" class="<%= is_active?(manage_passengers_path) %>">Hành khách</a>

      <% if current_user.user_role == "administrator" %>
        <a href="<%= users_path %>" class="<%= is_active?(users_path) %>">Thành viên</a>
      <% end %>
    </nav>

    <div class="site-header__user flex align-items--center">
      <img src="https://ui-avatars.com/api/?name=<%= current_user.email %>" alt="Profile">
      
      <div class="user">
        <div class="user-email"><%= current_user.email %></div>
        <%= link_to 'Đăng xuất', destroy_user_session_path, method: :delete %>
      </div>
    </div>
  </div>
</div>